apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: playbook-template
  title: Create a Ansible Playbook Project
  description: Create a starter Ansible Playbook project preconfigured for tests and pipelines. Includes Development settings and configuration for building an execution environment
  tags:
    - recommended
    - ansible
    - playbook
spec:
  owner: ansible-authors
  system: ansible
  type: service
  parameters:
    - title: Provide information about the new Ansible Project component
      required:
        - repoUrl
        - system
        - owner
        - projectGroup
        - projectName
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        description:
          title: Description
          type: string
          description: Describe this Project and its purpose to help other users know what to use it for
        projectGroup:
          title: Project group name
          description: The "ProjectOrg" part of "ProjectOrg.ProjectName"
          type: string
        projectName:
          title: Project name
          description: The "ProjectName" part of "ProjectOrg.ProjectName"
          type: string
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
  steps:
    - id: ansible
      name: Generating the Ansible Source Code Component
      action: ansible:content:create
      input:
        repoUrl: "${{ parameters.repoUrl }}"
        description: "${{ parameters.description }}"
        projectGroup: "${{ parameters.projectGroup }}"
        projectName: "${{ parameters.projectName }}"
        applicationType: Collection
        sourceControl: github.com

    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ./catalog-info-playbook/
        values:
          repoUrl: "${{ parameters.repoUrl }}"
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: Collection
          description: ${{ parameters.description }}
          projectGroup: ${{ parameters.projectGroup }}
          projectName: ${{ parameters.projectName }}
          sourceControl: github.com

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
