# Copyright Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and push image

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    name: Push plugin images to Quay
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    env:
      NODE_OPTIONS: --max-old-space-size=8192
      IMAGE_REGISTRY: quay.io/ansible
      IMAGE_NAME: ansible-backstage-plugins
      PR_IMAGE_PUSH: true
      REGISTRY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.QUAY_PASS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the last commit short SHA of the PR
        uses: ./.github/actions/get-sha

      - name: Determine Changed Files
        id: changes
        run: |
          if [[ '${{ github.event_name }}' == 'pull_request' ]]; then
            echo "IMAGE_TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV
            echo "COMMIT_IMAGE_TAG=pr-${{ github.event.number }}-$SHORT_SHA" >> $GITHUB_ENV

            BASE_COMMIT=${{ github.event.pull_request.base.sha }}
            HEAD_COMMIT=${{ github.event.pull_request.head.sha }}

            CHANGED_FILES=$(git diff --name-only "$BASE_COMMIT" "$HEAD_COMMIT")

            echo "Changed files:"
            echo "$CHANGED_FILES"

            # Check if changes are only in plugins/
            if echo "$CHANGED_FILES" | grep -qE '^plugins/'; then
                echo "Changes detected inside the plugins folder. Build required."
                echo "relevant_changes=true" >> $GITHUB_ENV
            else
                echo "No relevant changes detected. No build needed."
                echo "relevant_changes=false" >> $GITHUB_ENV
            fi
          else
            echo "IMAGE_TAG=main" >> $GITHUB_ENV
            echo "relevant_changes=true" >> $GITHUB_ENV
            echo "Running on the main branch. Build is needed."

          fi

      - name: Pack plugins
        if: env.relevant_changes == 'true'
        uses: ./.github/actions/pack

      - name: Run export-dynamic
        if: env.relevant_changes == 'true'
        run: |
          TAG=$IMAGE_TAG yarn export-dynamic

          if [ -n "$COMMIT_IMAGE_TAG" ]; then
            TAG=$COMMIT_IMAGE_TAG yarn export-dynamic
          fi

      - name: Login to Quay
        if: env.relevant_changes == 'true'
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Push To Quay
        id: push_to_quay
        if: env.relevant_changes == 'true'
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }} ${{ env.COMMIT_IMAGE_TAG }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Comment the image pull link
        if: env.relevant_changes == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The image for [${{ env.SHORT_SHA }}](https://github.com/ansible/ansible-backstage-plugins/pull/${{ github.event.number }}/commits/${{ github.event.pull_request.head.sha }}) is available at:\n* [`quay.io/ansible/ansible-backstage-plugins:${{ env.IMAGE_TAG }}`](https://quay.io/ansible/ansible-backstage-plugins:${{ env.IMAGE_TAG }})\n* [`quay.io/ansible/ansible-backstage-plugins:${{ env.COMMIT_IMAGE_TAG }}`](https://quay.io/ansible/ansible-backstage-plugins:${{ env.COMMIT_IMAGE_TAG }})'
            })
