name: PR

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  TURBO_SCM_BASE: ${{ github.event.pull_request.base.sha }}
  TURBO_SCM_HEAD: ${{ github.sha }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r .config/requirements.txt

      - name: Build Developer docs
        run: mkdocs build

  build:
    name: Build with Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Setup local Turbo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1 # v1

      - name: Yarn install (cached)
        uses: ./.github/actions/yarn-install
        with:
            cache-prefix: ${{ github.ref_name }}-${{ runner.os }}-${{ matrix.node-version }}

      - name: Build packages
        run: yarn run build

  test:
    name: Test with Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    permissions:
        actions: read
        checks: read
        contents: read
        id-token: write
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Setup local Turbo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@cc723b4600e40a6b8815b65701d8614b91e2669e # v1

      - name: Yarn install (cached)
        uses: ./.github/actions/yarn-install
        with:
            cache-prefix: ${{ github.ref_name }}-${{ runner.os }}-${{ matrix.node-version }}
  
      - name: Run Lint
        run: yarn lint:all

      - name: Run tests
        id: tests
        run: |
          yarn run test:all
          npx -y nyc report --reporter html --reporter text -t coverage --report-dir coverage/summary

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
          file: ./coverage/lcov.info
          fail_ci_if_error: false
          verbose: true

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.node-version }}
          path: ./coverage/lcov.info
        
      # Prepare Sonar arguments
      - name: Prepare Sonar arguments
        id: sonar-args
        run: |
            echo "SONAR_ARGS=-Dsonar.organization=ansible \
            -Dsonar.projectKey=ansible_ansible-backstage-plugins \
            -Dsonar.projectName='ansible-backstage-plugins' \
            -Dsonar.sources=plugins \
            -Dsonar.tests=plugins \
            -Dsonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.test.jsx \
            -Dsonar.exclusions=**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.test.jsx,**/.eslintrc.js \
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info" >> $GITHUB_ENV

      # SonarCloud Scan for PRs
      - name: SonarCloud Scan (Pull Request)
        if: github.event_name == 'pull_request'
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            ${{ env.SONAR_ARGS }}
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
            -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}            
  
  all-green:
    if: ${{ always() }}
    name: check
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert 'failure' not in
          set([
          '${{ needs.build.result }}',
          '${{ needs.test.result }}'
          ])"
          